import { cookies, headers } from 'next/headers'
import { pickLocale } from './request-locale-pure'
import type { OutputLocale } from './output-language'

/**
 * Locale for content generated by a request that has no deal yet (trial, deal
 * creation). Same precedence as the UI, so a first-time French visitor gets a
 * French analysis even before the language cookie exists.
 */
export async function resolveRequestLocale(bodyLocale?: unknown): Promise<OutputLocale> {
  const [cookieStore, headerStore] = await Promise.all([cookies(), headers()])
  return pickLocale({
    cookie: cookieStore.get('termlift_lang')?.value,
    body: bodyLocale,
    acceptLanguage: headerStore.get('accept-language'),
  })
}
